    # Identificación del proyecto
sonar.projectKey=HC-Backend
sonar.projectName=HC-Backend
sonar.projectVersion=1.0

# Código fuente
sonar.sources=.

# Excluir archivos innecesarios
sonar.exclusions=**/.terraform/**, **/__pycache__/**, **/*.pyc

# Config local
sonar.host.url=http://localhost:9000
sonar.token=sqp_9b9d069f160211ee81ef9c5fad9ca90474a3bbf6

# Python
sonar.python.version=3
