# ============================
# Identificación del proyecto
# ============================
sonar.projectKey=HC-Backend
sonar.projectName=HC-Backend
sonar.projectVersion=1.0

# ============================
# Código fuente
# ============================
sonar.sources=.

# Excluir archivos innecesarios
sonar.exclusions=**/.terraform/**, **/__pycache__/**, **/*.pyc

# ============================
# Config local SonarQube
# ============================
sonar.host.url=http://localhost:9000

# ============================
# Python
# ============================
sonar.python.version=3
sonar.sourceEncoding=UTF-8
